import { NextResponse } from "next/server";
import { ZodError } from "zod";
import logger from "@/shared/logger/logger";
import { prisma } from "@/shared/prisma/client";
import { randomUUID } from "crypto";
import { Difficulty, InterviewMode } from "@prisma/client";

const SetupAndStartSchema = {
  duration: "number",
  type: "string",
  source: "string",
  company: "string",
  role: "string",
  ownText: "string",
};

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { duration, type, source, company, role, ownText } = body;

    // Validate required fields
    if (!duration || !type || !source) {
      return NextResponse.json(
        { error: "Missing required fields: duration, type, source" },
        { status: 400 }
      );
    }

    if (source === 'own' && !ownText?.trim()) {
      return NextResponse.json(
        { error: "Problem statement is required when source is 'own'" },
        { status: 400 }
      );
    }

    let problemId: string;

    if (source === 'ai') {
      // For AI generation, we need to create a problem or use an existing one
      // For now, let's create a temporary problem from the AI generation
      // In a real implementation, this would call an AI service to generate the problem
      
      const problemTitle = `${type.toUpperCase()} Design - ${company || 'General'}`;
      const problemDescription = ownText || `AI-generated ${type} design problem for ${company || 'general'}. This is a placeholder - in production, this would be generated by AI based on the type, company, and role.`;
      const slug = `${type.toLowerCase()}-${company?.toLowerCase().replace(/\s+/g, '-') || 'general'}-${randomUUID().slice(0, 8)}`;
      
      // Create a new problem in the database
      const problem = await prisma.problem.create({
        data: {
          id: randomUUID(),
          title: problemTitle,
          description: problemDescription,
          difficulty: Difficulty.MEDIUM,
          category: type.toUpperCase(),
          interviewCount: 0,
          slug,
        },
      });
      
      problemId = problem.id;
    } else if (source === 'own') {
      // Create a problem from user's own text
      const slug = `custom-${type.toLowerCase()}-${randomUUID().slice(0, 8)}`;
      const problem = await prisma.problem.create({
        data: {
          id: randomUUID(),
          title: `Custom ${type.toUpperCase()} Problem`,
          description: ownText,
          difficulty: Difficulty.MEDIUM,
          category: type.toUpperCase(),
          interviewCount: 0,
          slug,
        },
      });
      
      problemId = problem.id;
    } else {
      return NextResponse.json(
        { error: "Invalid source. Must be 'ai' or 'own'" },
        { status: 400 }
      );
    }

    // Now call the existing interview start API
    const startPayload = {
      type: type.toLowerCase(),
      difficulty: Difficulty.MEDIUM,
      duration: duration,
      company: company || 'General',
      problemId: problemId,
      mode: InterviewMode.CANDIDATE,
    };

    const interviewService = (await import("@/features/interview")).InterviewService;
    const service = new interviewService();
    const interviewId = await service.startInterview(startPayload);

    return NextResponse.json({ id: interviewId }, { status: 201 });
  } catch (error) {
    if (error instanceof ZodError) {
      logger.error("Validation Error", { issues: error.issues });
      return NextResponse.json(
        { error: "Invalid request body", issues: error.issues },
        { status: 400 }
      );
    }

    logger.error("Failed to setup and start interview", { error });
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
