export enum ArtifactType {
  LOG = "LOG",
  METRIC = "METRIC",
  TRACE = "TRACE",
  SQL = "SQL",
  CODE = "CODE",
  CONFIG = "CONFIG",
  API_RESPONSE = "API_RESPONSE",
  DASHBOARD = "DASHBOARD",
  TERMINAL = "TERMINAL",
  SCREENSHOT = "SCREENSHOT",
}